backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

collections:
  - name: "home-sections"
    label: "Home sections"
    folder: "src/cms/home"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Data Key", name: "dataKey", widget: "hidden", default: "home-sections"}
      - {label: "Theme", name: "theme", widget: "select", default: "dark", options: ["dark", "light"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show title", name: "isTitleVisible", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Text Position", name: "textPosition", widget: "select", required: false, options: ["left", "right", "center"]}
      - {label: "Image", name: "sectionImage", widget: "object", required: false, fields: [
          {label: "Title", name: "title", widget: "string", required: false},
          {label: "Image", name: "image", widget: "image", required: false},
          {label: "Alternative text", name: "alt", widget: "string", required: false},
          {label: "Position", name: "position", widget: "select", default: "right", required: false, options: ["left", "right", "background"]},
          {label: "Max Height (pixels)", name: "maxHeight", widget: "number", required: false},
          {label: "Url", name: "url", widget: "string", required: false},
          {label: "Internal link", name: "isInternal", widget: "boolean", required: false}
        ]}
      - {label: "Cards", name: "cards", widget: "list", required: false, fields: [
          {label: "Title", name: "title", widget: "string"},
          {label: "Type", name: "type", widget: "select", default: "vertical", options: ["vertical", "horizontal", "carousel"]},
          {label: "Image", name: "image", widget: "image"},
          {label: "Alternative text", name: "alt", widget: "string", required: false},
          {label: "Text", name: "text", widget: "text", required: false}
        ]}
      - {label: "Call-To-Action", name: "cta", widget: "object", required: false, fields: [
          {label: "Label", name: "label", widget: "string", required: false},
          {label: "Url", name: "url", widget: "string", required: false},
          {label: "Internal link", name: "isInternal", widget: "boolean", required: false}
        ]}

  - name: "product-categories"
    label: "Product categories"
    folder: "src/cms/products/categories"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Data Key", name: "dataKey", widget: "hidden", default: "product-categories"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Position", name: "position", widget: "number", default: 50}

  - name: "blog"
    label: "Blog"
    folder: "src/cms/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/cms/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Main Call-To-Action", name: "mainCta", widget: "object", required: false, fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "Url", name: "url", widget: "string"},
              {label: "Internal link", name: "isInternal", widget: "boolean"}
            ]}
          - {label: "Sections", name: "sections", widget: "list", fields: [
              {label: "Section", name: "section", widget: "relation", collection: "home-sections", searchFields: ["title"], valueField: "title"}
            ]}

      - file: "src/cms/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Redirect link", name: "redirectLink", widget: "object", fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "Url", name: "url", widget: "string"},
              {label: "Internal link", name: "isInternal", widget: "boolean"}
            ]}

      - file: "src/cms/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Packages", name: "packages", widget: "object", fields: [
              {label: "Step name", name: "stepName", widget: "string"},
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Description", name: "description", widget: "text", required: false, default: ''},
              {label: "Plans", name: "plans", widget: "list", fields: [
                  {label: "Plan", name: "plan", widget: "string"},
                  {label: "Category", name: "category", widget: "relation", collection: "product-categories", searchFields: ["title"], valueField: "title"},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Price", name: "price", widget: "number", default: 0},
                  {label: "Frequency", name: "frequency", widget: "string", required: false},
                  {label: "Description", name: "description", widget: "string", required: false},
                  {label: "Benefits", name: "benefits", widget: "list", field: {label: "Benefit", name: "benefit", widget: "string"}}
                ]
              }
            ]}
          - {label: "Date and time choice", name: "dateTimeScreen", widget: "object", fields: [
              {label: "Step name", name: "stepName", widget: "string"},
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Description", name: "description", widget: "text", required: false, default: ''},
              {label: "Available timeslots", name: "availableTimeslots", widget: "list", fields: [
                  {label: "Start", name: "start", widget: "datetime", dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm", format: "LLL"},
                  {label: "End", name: "end", widget: "datetime", dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm", format: "LLL"}
                ]
              }
            ]}
          - {label: "Location choice", name: "locationScreen", widget: "object", fields: [
              {label: "Step name", name: "stepName", widget: "string"},
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Description", name: "description", widget: "text", required: false, default: ''},
              {label: "Labels", name: "contribution", widget: "object", fields: [
                {label: "Location choice custom place label", name: "locationChoiceCustomPlaceLabel", widget: "string", default: 'At your place'},
                {label: "Location choice label", name: "locationChoiceLabel", widget: "string", default: 'Your preferred place'},
                {label: "Location choice error", name: "locationChoiceError", widget: "text", default: 'Please select a place to meet or provide your own place'},
                {label: "Customer place label", name: "customerPlaceLabel", widget: "string", default: 'Choose a place'},
                {label: "Customer place placeholder", name: "customerPlacePlaceholder", widget: "string", default: '1 rue du général Leclerc ...'},
                {label: "Customer place error", name: "customerPlaceError", widget: "text", default: 'We are missing an address to meet'}
              ]},
              {label: "Available locations", name: "availableLocations", widget: "list", fields: [
                  {label: "Label", name: "label", widget: "string"},
                  {label: "Address", name: "address", widget: "string"}
                ]
              }
            ]}
          - {label: "Confirmation screen", name: "confirmationScreen", widget: "object", fields: [
              {label: "Step name", name: "stepName", widget: "string"},
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Description", name: "description", widget: "text", required: false, default: ''},
              {label: "Labels", name: "contribution", widget: "object", fields: [
                {label: "Plan choice label", name: "planChoiceLabel", widget: "string", default: 'Plan chosen'},
                {label: "Date choice label", name: "dateChoiceLabel", widget: "string", default: 'Date'},
                {label: "Location choice label", name: "locationChoiceLabel", widget: "string", default: 'Place'},
                {label: "Validation button label", name: "validationButtonLabel", widget: "string", default: 'Schedule our meeting'},
                {label: "Email label", name: "emailLabel", widget: "string", default: 'Email'},
                {label: "Email placeholder", name: "emailPlaceholder", widget: "string", default: 'john.doe@gmail.com'},
                {label: "Firstname label", name: "firstNameLabel", widget: "string", default: 'First name'},
                {label: "Firstname placeholder", name: "firstNamePlaceholder", widget: "string", default: 'John'},
                {label: "Lastname label", name: "lastNameLabel", widget: "string", default: 'Last name'},
                {label: "Lastname placeholder", name: "lastNamePlaceholder", widget: "string", default: 'Doe'},
                {label: "Additional informations label", name: "additionalInfoLabel", widget: "string", default: 'Any questions or note ?'},
                {label: "Additional informations placeholder", name: "additionalInfoPlaceholder", widget: "string", default: 'Feel free to ask any question here'},
                {label: "Required field error message", name: "requiredErrorMessage", widget: "text", default: 'You must answer here'}
              ]},
            ]}
          - {label: "Thank you screen", name: "thankYouScreen", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Content", name: "content", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Redirect link", name: "redirectLink", widget: "object", fields: [
                {label: "Label", name: "label", widget: "string"},
                {label: "Url", name: "url", widget: "string"},
                {label: "Internal link", name: "isInternal", widget: "boolean"}
              ]}
            ]}
